### ISSUE TITLE
fletch reset

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/fletch#172]
If something hangs, you have to ```killall dart```. Would be good to have something like ```fletch reset``` or ```fletch abort``` instead.

**Comment by peter-ahe-google** [comment]
@lukechurch Suggestions for verb name?

**Comment by peter-ahe-google** [comment]
I like `fletch force quit`, but I'm a Mac user. Perhaps `fletch quit` or `fletch exit` for Mac and Windows users respectively.

**Comment by lukechurch** [comment]
As discussed
```
fletch force quit
```
To terminate everything, whether or not it is 'responding'. In the future 
```
fletch shutdown all
```
Will politely request all of the clients to close.

**Comment by peter-ahe-google** [comment]
After further considerations, we realized that `fletch quit` would be fine. Rather than having two quit commands (one for `kill` and one for `kill -9`) we realized that we just need one command that will first attempt `kill`. If the persistent process hasn't exited after 2 seconds, the command will use `kill -9`.

**Comment by peter-ahe-google** [comment]
Proposed fix in [CL 1374043006](https://codereview.chromium.org/1374043006/)
