### ISSUE TITLE
fletch-vm should remove any pid and port files created at startup

### ISSUE THREAD

**Issue by wibling** [dart-lang/fletch#216]
If starting the fletch-vm with the --run-dir option it will create a pid and a port file in /var/run/fletch-agent (or more precisely in the directory it reads from the VM_PID_DIR environment variable).

We should clean these up on exit or investigate if we can avoid having these files altogether. E.g. by using sockets/pipes to communicate the information back to the agent when spawning.

**Comment by mkustermann** [comment]
If we introduce more files (e.g. `.fletch`, `.fletch.pid`, `fletch-settings`, ...) it would be an option to put these into a common directory (e.g. `$HOME/.fletch/*` or `$HOME/.config/fletch/*`) and have **a single environment variable** like FLETCH_HOME instead of having several environment variables.

@peter-ahe-google

**Comment by peter-ahe-google** [comment]
As we want to run the fletch agent locally as well, I think @mkustermann's suggestion makes a lot of sense.

**Comment by wibling** [comment]
Instead of adding more files I got rid of the pid and port files.
