### ISSUE TITLE
language/vm/regress_24517_test is flaky

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/fletch#333]
It fails for me locally (runtimeerror),  but seems to pass on the bots (eg. https://uberchromegw.corp.google.com/i/client.fletch/builders/target-fletch-linux-debug-arm/builds/199/steps/Test%20DebugXARM/logs/stdio).

This test only exists after the roll of https://codereview.chromium.org/1450393002/

**Comment by mkustermann** [comment]
This test is not flaky, it just behaves differently in different configurations. It is a floating point rounding issue with `sqrt()`.

Turns out that gcc `-O0` code will just call the C `sqrt` function, and `-O3` code uses `fsqrt` on 32-bit and `sqrtsd` on 64-bit.

The `fsqrt` on intel will use 80-bit wide floating point, which makes it round differently.
