### ISSUE TITLE
Configurable package root

### ISSUE THREAD

**Issue by zerny** [dart-lang/fletch#44]
Add a package root option to fletch/fletch-driver a package directory can be used from different locations.

Currently tests/service_tests/conformance/java/Makefile compiles snapshots with a different cwd than the fletch root and needs to be configures to use the package directory from the fletch root.

**Comment by skabet** [comment]
Peter, I suppose we can do this as part of merging the driver/non-driver interface?

**Comment by peter-ahe-google** [comment]
Yes, now seems like a good time to implement this.

**Comment by skabet** [comment]
@zerny fixed the issue in c87486dbf9a1d065b30bce3dcce1b505a1ae2dbc.

**Comment by peter-ahe-google** [comment]
Still not fixed for fletch (née fletch-driver).

**Comment by peter-ahe-google** [comment]
@lukechurch I guess we need a UI for this. Any ideas? I would like something that works with incremental compilation, so I suggest:

    fletch set packages <file>

**Comment by peter-ahe-google** [comment]
The solution is to have a settings file. It will be JSON and it contains a list of compile-time constants and the packages location.

I think this layout should suffice:

```json
{
  "packages": "relatative URI to .packages file",
  "constants": {
    "name": "value"
  }
}
```
When creating a session, one can specify a settings file:

```console
$ fletch create session my_session with settings.json
```

If no settings file is specified when creating a session, we use the file `.fletch-settings.json` if it exists.

**Comment by peter-ahe-google** [comment]
Propose fix: [CL 1354253003](https://codereview.chromium.org/1354253003/)

**Comment by peter-ahe-google** [comment]
Using this format:

```
{
  "package root": "A relative URI to the package root",
  "package root": "package",

  "options": "A list of strings that are passed to the compiler",
  "options": null,

  "contants": "A map of compile-time constants",
  "constants": null
}
```

**Comment by skabet** [comment]
Why is this a settings file instead of a command line option?

**Comment by peter-ahe-google** [comment]
The motivation for the settings file is that package root, compile-time constants (those from String.fromEnvironment, etc), and other compiler options need to be be part of the incremental compilation. When one of these values change, it can impact the output of the compiler.

I'm sure it is obvious to you that when the value of compile-time constant changes, we need to compute a new FletchSystem with those constants in mind. I think something similar happens when you change the package root, but in this case it is more like a bunch of files got added, removed, or modified. In either case, we need to compute a new FletchSystem.

So I think it is important that a user (a developer that uses Fletch) is aware that changing any of those settings changes the session/program/FletchSystem.

Another issue is that if these settings were controlled with options, when should you supply the options? The first time you compile? The second time? What happens if you forget an option? What happens if the persistent process crashes?
